<a href="https://colab.research.google.com/github/Shubham829KIIT/Framingham-H-disease/blob/main/Logistic_Regression_(ANN).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from tensorflow import keras


In [ ]:
df_main=pd.read_csv("framingham.csv")
df_main.shape

(4238, 16)

In [ ]:
df_main.head(3)

male  age  education  currentSmoker  cigsPerDay  BPMeds  prevalentStroke  \
0     1   39        4.0              0         0.0     0.0                0   
1     0   46        2.0              0         0.0     0.0                0   
2     1   48        1.0              1        20.0     0.0                0   

   prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  heartRate  glucose  \
0             0         0    195.0  106.0   70.0  26.97       80.0     77.0   
1             0         0    250.0  121.0   81.0  28.73       95.0     76.0   
2             0         0    245.0  127.5   80.0  25.34       75.0     70.0   

   TenYearCHD  
0           0  
1           0  
2           0

## Count the number of Null values in each column

In [ ]:
df_main.isnull().sum()

male                 0
age                  0
education          105
currentSmoker        0
cigsPerDay          29
BPMeds              53
prevalentStroke      0
prevalentHyp         0
diabetes             0
totChol             50
sysBP                0
diaBP                0
BMI                 19
heartRate            1
glucose            388
TenYearCHD           0
dtype: int64

In [ ]:
df_main.isnull()

male    age  education  currentSmoker  cigsPerDay  BPMeds  \
0     False  False      False          False       False   False   
1     False  False      False          False       False   False   
2     False  False      False          False       False   False   
3     False  False      False          False       False   False   
4     False  False      False          False       False   False   
...     ...    ...        ...            ...         ...     ...   
4233  False  False      False          False       False   False   
4234  False  False      False          False       False   False   
4235  False  False      False          False       False    True   
4236  False  False      False          False       False   False   
4237  False  False      False          False       False   False   

      prevalentStroke  prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  \
0               False         False     False    False  False  False  False   
1               False         False     False    False  False  False  False   
2               False         False     False    False  False  False  False   
3               False         False     False    False  False  False  False   
4               False         False     False    False  False  False  False   
...               ...           ...       ...      ...    ...    ...    ...   
4233            False         False     False    False  False  False  False   
4234            False         False     False    False  False  False  False   
4235            False         False     False    False  False  False  False   
4236            False         False     False    False  False  False  False   
4237            False         False     False    False  False  False  False   

      heartRate  glucose  TenYearCHD  
0         False    False       False  
1         False    False       False  
2         False    False       False  
3         False    False       False  
4         False    False       False  
...         ...      ...         ...  
4233      False    False       False  
4234      False    False       False  
4235      False    False       False  
4236      False     True       False  
4237      False    False       False  

[4238 rows x 16 columns]

## Counting the number of rows in which atleast one of the attribute is empty

In [ ]:

ct=df_main.isnull().any(axis=1).sum()
print("Number of empty rows:", ct)


Number of empty rows: 582


In [ ]:
df_main.shape

(4238, 16)

In [ ]:
df_main.columns.dtype

dtype('O')

## Taking care of Numeric missing values

In [ ]:
X = df_main.iloc[:,:-1].values
y = df_main.iloc[:,-1].values
print(X)
print(y)

[[  1.    39.     4.   ...  26.97  80.    77.  ]
 [  0.    46.     2.   ...  28.73  95.    76.  ]
 [  1.    48.     1.   ...  25.34  75.    70.  ]
 ...
 [  0.    48.     2.   ...  22.    84.    86.  ]
 [  0.    44.     1.   ...  19.16  86.      nan]
 [  0.    52.     2.   ...  21.47  80.   107.  ]]
[0 0 0 ... 0 0 0]


In [ ]:
from sklearn.impute import SimpleImputer
import numpy as np

In [ ]:
imputer=SimpleImputer (missing_values=np.nan,strategy="mean")
imputer.fit(X[:,2:15])
X[:,2:15]=imputer.transform(X[:,2:15])

In [ ]:
X

array([[  1.        ,  39.        ,   4.        , ...,  26.97      ,
         80.        ,  77.        ],
       [  0.        ,  46.        ,   2.        , ...,  28.73      ,
         95.        ,  76.        ],
       [  1.        ,  48.        ,   1.        , ...,  25.34      ,
         75.        ,  70.        ],
       ...,
       [  0.        ,  48.        ,   2.        , ...,  22.        ,
         84.        ,  86.        ],
       [  0.        ,  44.        ,   1.        , ...,  19.16      ,
         86.        ,  81.96675325],
       [  0.        ,  52.        ,   2.        , ...,  21.47      ,
         80.        , 107.        ]])

## Performing Label Encoding operations

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2]= le.fit_transform(X[:,2])

## Splitting the dataframe into training and testing

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state =0)

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [ ]:
y_test

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

## Modelling the ANN architecture

In [ ]:
from tensorflow import keras
import tensorflow as tf
model=tf.keras.models.Sequential()
model.add(keras.layers.Dense(15,activation="sigmoid"))
keras.layers.Dropout(0.5)
model.add(keras.layers.Dense(20,activation="tanh"))
keras.layers.Dropout(0.5)
model.add(keras.layers.Dense(10,activation="tanh"))
keras.layers.Dropout(0.5)
model.add(keras.layers.Dense(10,activation="tanh"))
keras.layers.Dropout(0.5)
model.add(keras.layers.Dense(1,activation="sigmoid"))
model.compile (optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])

In [ ]:
x_train.shape

(3390, 15)

In [ ]:
y_train.shape

(3390,)

In [ ]:
model.fit(x_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
106/106 [==============================] - 2s 2ms/step - loss: 0.4599 - accuracy: 0.8153
Epoch 2/100
106/106 [==============================] - 0s 2ms/step - loss: 0.3907 - accuracy: 0.8510
Epoch 3/100
106/106 [==============================] - 0s 2ms/step - loss: 0.3848 - accuracy: 0.8531
Epoch 4/100
106/106 [==============================] - 0s 2ms/step - loss: 0.3833 - accuracy: 0.8549
Epoch 5/100
106/106 [==============================] - 0s 2ms/step - loss: 0.3813 - accuracy: 0.8540
Epoch 6/100
106/106 [==============================] - 0s 4ms/step - loss: 0.3803 - accuracy: 0.8558
Epoch 7/100
106/106 [==============================] - 0s 3ms/step - loss: 0.3805 - accuracy: 0.8531
Epoch 8/100
106/106 [==============================] - 0s 5ms/step - loss: 0.3793 - accuracy: 0.8563
Epoch 9/100
106/106 [==============================] - 1s 7ms/step - loss: 0.3811 - accuracy: 0.8549
Epoch 10/100
106/106 [==============================] - 1s 6ms/step - loss: 0.3781 - accura

In [ ]:
y_pred = model.predict(x_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

27/27 [==============================] - 0s 2ms/step
[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.8419811320754716